name: 'LFS-warning'
on: [push, pull_request]
jobs:
    uses: actionsdesk/lfs-warning@v2.0
with:
  filesizelimit:  '1000000' # id of input 
      description: 'file size limit threshold'
  outputs:
    lfsFiles: # output will be available to future steps 
      description: 'Array of possible detected large file(s)'
  runs:
    using: 'node12'
    main: 'dist/index.js'
  branding:
    icon: 'alert-triangle' # icon referenced from https://feathericons.com/
    color: 'yellow'
