name: 'LFS-warning'
on: [push, pull_request]
jobs:
    uses: actionsdesk/lfs-warning@v2.0
    with:
    token:
      required: false
      description: Token used to fetch the repository
      default: ${{ github.token }}
    filesizelimit:  # id of input 
      description: 'file size limit threshold'
      required: true
      default: '1000000' # 1 MB is 100000 Bytes 
  outputs:
    lfsFiles: # output will be available to future steps 
      description: 'Array of possible detected large file(s)'
  runs:
    using: 'node12'
    main: 'dist/index.js'
  branding:
    icon: 'alert-triangle' # icon referenced from https://feathericons.com/
    color: 'yellow'
